### ISSUE TITLE
Clipping with Better Portals

### ISSUE THREAD

**Issue by M0DSteam** [Kaydax/Ido#11]
If you create a horizontal nether portal in the floor using [Better Portals](https://www.curseforge.com/minecraft/mc-mods/betterportals) you can enter normally from the upper side, but when trying to get out of the nether from below, you just clip into the blocks from the other dimension (the overworld), making you suffocate and subsequently, die.

To Recreate This: you gotta have both Better Portals and Idō installed, create a horizontal portal in the floor and try to enter from above to the nether and then return to the overworld from below in survival (I believe that is may even happen when trying to do it with creative flying, but I haven't tested).

I didn't take any picture for now, but I'll get some if they are required.

I hope I was clear with this and it isn't confusing, thanks :)

**Comment by Kaydax** [comment]
Pictures are always welcome, so send some over so I can see whats happening on your end and to allow me to recreate it when testing.

**Comment by M0DSteam** [comment]
instead of taking pictures I recorded a video https://streamable.com/mgka4
I hope this is useful

**Comment by Johni0702** [comment]
You're using `World.collidesWithAnyBlock(AABB)` to check for bounding boxes, consider using `World.getCollisionBoxes(Entity, AABB)` instead.
BP needs to know which entity the BB are being queried for because they're different depending on which side of the portal it is standing.
Additionally getCollisionBoxes will also return solid collision boxes of entities (e.g. shulker, boat, etc.) which I believe is what you want anyway.

https://github.com/Kaydax/Ido/blob/cc2af3b988ec2b02b696567cbbecac506e0651ed/src/main/java/xyz/kaydax/ido/handler/ClientHandler.java#L75
https://github.com/Kaydax/Ido/blob/cc2af3b988ec2b02b696567cbbecac506e0651ed/src/main/java/xyz/kaydax/ido/handler/ClientHandler.java#L82

**Comment by Kaydax** [comment]
Issue should be fixed in the next update
