### ISSUE TITLE
IDO and Howling Moon

### ISSUE THREAD

**Issue by Traincrafter111** [Kaydax/Ido#37]
Hi there is a bug that makes that if you have howling moon and Ido and you transform into a wolf or a beast the camara dont adjust and it stays at 2 blocks hight (normal steve hight) doesnt increase or decrease
![2019-10-22_17 43 42](https://user-images.githubusercontent.com/44734869/67340776-cf14fc00-f4f3-11e9-9378-7aedad7aeb28.png)

**Comment by Kaydax** [comment]
So after checking If I could patch this in any way, there seems to be no source code available for this mod, thus making my job harder. Since this reason I'm closing this issue and this mod will stay incompatible unless the creator of Howling Moon decides to either make a patch for it himself or provide source code
