### ISSUE TITLE
Incorrect animation when walking with repose mod installed

### ISSUE THREAD

**Issue by ChrissPz** [Kaydax/Ido#9]
What happens in this case is that when the player walking with repose mod installed at half-block of climb makes an animation of swimming when in reality it shouldn't happen because obviously we are walking right? then instead of routinely walk this is interrupted by the innocent animation of swimming.

ignore my igor skin i don't like it.. my cousin changed it lol
![2019-07-26_04 44 11](https://user-images.githubusercontent.com/33664951/61936333-7f597f80-af5a-11e9-8143-9d37eedeffd5.png)
![2019-07-26_04 42 51](https://user-images.githubusercontent.com/33664951/61936334-7f597f80-af5a-11e9-8507-da9974435bfe.png)
![2019-07-26_04 43 40](https://user-images.githubusercontent.com/33664951/61936336-7ff21600-af5a-11e9-9e0d-c3e53f08f382.png)
![2019-07-26_04 43 46](https://user-images.githubusercontent.com/33664951/61936337-7ff21600-af5a-11e9-852a-7838e7e9ba3e.png)

I expect a solution, if I worry it's because I like the mod.

**Comment by Kaydax** [comment]
Yah with the way repose works I can't fix it without tons of work to rewrite half of this mod. Because repose makes the player clip into the block while walking up it, thus making ido think you are inside of a block when doing collision checks. I may see what I can do later on down the road, but for now I don't see how I can fix this.
